services:
  frontend:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: fe-cms-project-kkn
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - private-net
    env_file:
      - .env

networks:
  private-net:
    external: true
