services:
  frontend:
    build:
      context: .
      args:
        - VITE_API_URL:http://localhost:3000
    container_name: fe-cms-project-kkn
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - private_net

networks:
  private_net:
    external: true
